version: "3.8"
services:
  zip-temperature:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash .docker/start.sh
    restart: "no"
    container_name: "zip-temperature"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app